# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:pidfile: ./tmp/pids/sidekiq.pid
production: 
  :concurrency: 10
  :daemon: true
  :verbose: false
  :logfile: ./log/sidekiq.log
  :timeout: 120
  :timeout: 30
development:
  :concurrency: 10
  :verbose: true
  :queues: 
    - products
    - reports
